ablog/ablog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('theblog.urls')),
    path ('members/',include('django.contrib.auth.urls')),
    path('members/',include('members.urls')),
    
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ablog/members/urls.py
from django.urls import path
from .views import *
#from django.contrib.auth import views as auth_views

app_name = "signup"

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('edit_profile/', UseEditView.as_view(), name='edit_profile'),
    #path('password/',auth_views.PasswordChangeView.as_view(template_name='registration/change-password.html'))
    path('password/', PasswordsChangeView.as_view(template_name='registration/change-password.html'), name='password_change'),
    path('<int:pk>/profile', ShowProfilePageView.as_view(), name="show_profile_page"),
    path('<int:pk>/edit_profile_page', editProfilePageView.as_view(), name="edit_profile_page"),
    path('<create_profile_page', CreateProfilePageView.as_view(), name="CreateProfilePageView"),


]

ablog/theblog/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "home"

urlpatterns = [
    #path('',views.HomeView , name="HomeView")
    path('', HomeView.as_view() , name="home"),
    path('addPost/', AddPostView.as_view() , name="addPost"),
    path('article/<int:pk>' , ArticleDetailView.as_view() , name="detail"),
    path('article/edit/<int:pk>', UpdatePost.as_view() ,name="update" ),
    path('addCategory/', AddCategory.as_view() , name="addCategory"),
    path('article/delete/<int:pk>', DetelePost.as_view() ,name="delete" ),
    path('category/<str:cats>/', views.categoryViews,name="categoryViews"),
    path('category/', CategoryView.as_view(),name="category"),
    path('likes/<int:pk>', views.likeView, name="like_post"),
    path('article/<int:pk>/comment',AddCommentView.as_view(),name='add_comment')
]

ablog/theblog/models.py
from django.db import models
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from datetime import datetime,date
from ckeditor.fields import RichTextField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('home:home')


class Post(models.Model):
    title = models.CharField(max_length=255)
    title_tag = models.CharField(max_length=60)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    category = models.CharField(max_length=100)
    body = RichTextField(blank=True,null=True)
    #body = models.TextField()
    post_date = models.DateField(auto_now_add=True)
    snippet = models.CharField(max_length=300)
    #category = models.ForeignKey(Category,on_delete=models.CASCADE, default=2)
    likes = models.ManyToManyField(User, related_name="blog_post")
    header_image = models.ImageField(null=True, blank=True , upload_to="image/")



    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return f"{self.title} | {self.author}"

    def get_absolute_url(self):
        return reverse("home:detail", args= (self.id,))
        #return reverse('home:home')

class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    profile_pics = models.ImageField(null=True, blank=True , upload_to="image/profile/")
    linkedin_url = models.CharField(max_length=255, null=True, blank=True)
    bio = models.TextField()

    def __str__(self):
        return f"{self.user}"
    
    def get_absolute_url(self):
    #return reverse("home:detail", args= (self.id,))
        return reverse('home:home')

class Comment(models.Model):
    post = models.ForeignKey(Post,related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.post.title} , {self.name}"

ablog/theblog/views.py
from django.shortcuts import render,get_object_or_404
from django.urls import reverse_lazy,reverse
from .models import Post,Category,Comment
from .form import PostForm,editForm,AddCommentForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView,ListView,DetailView,CreateView,DeleteView
from django.http import HttpResponseRedirect

# Create your views here.

""" def home(request):
    return render(request,'home.html',{})
 """
class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-post_date']
    #ordering = ['-id']

    def get_context_data(self, *args,**kwargs):
        cat_menu = Category.objects.all()
        context = super(HomeView,self).get_context_data(*args,**kwargs)
        context["cat_menu"] = cat_menu
        return context


class ArticleDetailView(DetailView):
    model = Post
    template_name = 'article_detail.html'

    def get_context_data(self, *args,**kwargs):
        context = super(ArticleDetailView,self).get_context_data(*args,**kwargs)
        like = get_object_or_404(Post,id=self.kwargs['pk'])
        liked = False
        if like.likes.filter(id=self.request.user.id).exists():
            liked = True
        likes = like.total_likes()
        context['likes'] = likes
        context['liked'] = liked
        return context



class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post.html'
    #fields = '__all__'

class UpdatePost(UpdateView):
    model = Post
    form_class = editForm
    template_name = 'editPost.html'
    #fields = ['title','title_tag','body']

class DetelePost(DeleteView):
    model = Post
    template_name = 'deletePost.html'
    success_url = reverse_lazy('home:home')

class AddCategory(CreateView):
    model = Category
    template_name = 'addCategory.html'
    fields = '__all__'
    
def categoryViews(request,cats):
    Category_posts = Post.objects.filter(category=cats.replace('-',' '))
    return render (request,'category.html',{"cats":cats.title().replace('-',' '), "category_post":Category_posts})


class CategoryView(ListView):
    model = Category
    template_name = 'category_page.html'

def likeView(request,pk):
    post = get_object_or_404(Post, id=request.POST.get('postLike'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
    else:
        post.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse("home:detail", args=(pk,)))


class AddCommentView(CreateView):
    model = Comment
    form_class = AddCommentForm
    #fields = '__all__'
    template_name = 'add_comment.html'

    def form_valid(self,form):
        form.instance.post_id = self.kwargs['pk']
        return super().form_valid(form)

    success_url = reverse_lazy('home:home')

ablog/theblog/templates/addCategory.html
{% extends 'base.html' %}

{% block title %}
    add category
{% endblock %}

{% block content %}
<!-- {% if user.is_authenticated %}
 -->    <h1>Add category...</h1>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-secondary">add category</button>
        </form>
        <br>
        <a class="btn btn-secondary" href="{% url 'home:home' %}">Home</a>
    </div>
<!-- {% else %}
<p>Login is required</p>
<a href="{% url 'login' %}">Login Page!</a>
{% endif %}
 -->{% endblock %}

ablog/theblog/templates/add_comment.html
{% extends 'base.html' %}

{% block title %}
    add comment
{% endblock %}

{% block content %}
    <h1>Add comment...</h1>
    <div class="form-group">
        <form method="POST" >
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-secondary">add comment</button>
        </form>
        <br>
        <a class="btn btn-secondary" href="{% url 'home:home' %}">Home</a>
    </div>
{% endblock %}

ablog/theblog/templates/article_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{post.title_tag}}
{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <small> by : {{ post.author}}</small><br>
    {{post.post_date}}
    <hr>
    {% if post.header_image %}
        <img src="{{ post.header_image.url }}">
    {% endif %}
    <br><br/>
    {{ post.body|safe }}
    <br><br>
    {% if user.is_authenticated %}
        <form action="{% url 'home:like_post' post.pk %}" method="POST">
            {% csrf_token %}
            {% if liked %}
                <button type="submit" name="postLike" value="{{ post.pk }}" class="btn btn-primary">Unlikes</button> {{likes}} likes
            {% else %}
                <button type="submit" name="postLike" value="{{ post.pk }}" class="btn btn-secondary">Likes</button> {{likes}} likes
            {% endif %}
        </form>
    {% else %}
        <button id="click" class="btn btn-secondary">Likes</button> {{likes}} likes
        <a style="display: none;" href="{% url 'login' %}" id="signUpButton" class="btn btn-secondary">login needed for like</a>
        <script>
            function show() {
                document.getElementById('signUpButton').style.display = "block";
            }
            document.getElementById('click').onclick = show
        </script>
    {% endif %}
    <br><br>
    <a class="btn btn-secondary" href="{% url 'home:home' %}">home</a>
    <br><br>
    {% if user.is_authenticated and user.id == post.author.id %}
        <a class="btn btn-secondary" href="{% url 'home:delete' post.id %}">Delete</a>
    {% endif %}
    <p></p>
    <hr>
    <div class="card mb-3">
        <div class="row no-gutters">
          <div class="col-md-4">
            {% if post.author.profile.profile_pics %}
                <img src="{{post.author.profile.profile_pics.url }}" style="width: 200px; height: 200px;" alt="Profile">
            {% else %}
                <img src="{% static 'blog/img/photo.png' %}" style="width: 200px; height: 200px;">
            {% endif %}
        </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title">Profile pics</h5><br>
              <a href="{%url 'signup:show_profile_page' post.author.profile.id %}">profile page</a>
              <p class="card-text">{{ post.author.profile.bio}}</p>
              {% if post.author.profile.linkedin_url %}
              <a class="card-text" href="{{post.author.profile.linkedin_url }}">linkedin</a></small></a>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    <hr>
    <h3>comments</h3>
    {% if not post.comments.all %}
        No comment yet.... <a href="{% url 'home:add_comment' post.pk %}">click here</a>
    {% else %}
        <a href="{% url 'home:add_comment' post.pk %}">add comment</a>
        {% for comment in post.comments.all %}
            <br>{{ comment.name}} - {{comment.date_added}}<br>
            {{ comment.body }}
        {% endfor %}
    {% endif %}
    <br/><br/>
    <hr>
  
{% endblock %}

ablog/theblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>
        {% block title %}
        {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home:home' %}">My blog 
          {% if user.is_authenticated %}
            {{user.username}}
          {% endif %}            
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <!-- category Menu code -->
            {% if cat_menu %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Category
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% for item in cat_menu %}
                  <a class="dropdown-item" href="{% url 'home:categoryViews' item|slugify %}">{{item}}</a>
                {% endfor %}
              </div>
            </li>
            {% endif %}
            
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:addPost' %}">Add Post</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:addCategory' %}">Add Category</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home:category' %}">Category</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'signup:edit_profile' %}">Edit setting</a>
                  {% if user.profile.id %}
                    <a class="dropdown-item" href="{% url 'signup:edit_profile_page' user.profile.id %}"> edit profile</a>
                    <a class="dropdown-item" href="{% url 'signup:show_profile_page' user.profile.id %}">profile</a>
                  {% else %}
                    <a class="dropdown-item" href="{% url 'signup:CreateProfilePageView' %}"> create profile</a>
                  {% endif %}
                </li>
<!--               <li class="nav-item">
                <a class="nav-link" href="{% url 'signup:edit_profile' %}">Profile</a>
              </li>  -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li> 
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:category' %}">Category</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'signup:register' %}">SignUp</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

ablog/theblog/templates/category.html
{% extends 'base.html' %}

{% block title %}
    {{ cats }}
{% endblock %}

{% block content %}
<h1>{{ cats }}</h1>

<ul>
    {% for post in category_post %}
        <li> 
            <a href="{% url 'home:detail' post.pk %}"> title :{{ post.title }}</a><br>Category <a href="{% url 'home:categoryViews' post.category %}">{{post.category}}</a><br>
            author :  {{ post.author}}  
            {% if user.is_authenticated %}
                -<a href="{% url 'home:update' post.pk%}">edit</a>|| <a href="{% url 'home:delete' post.pk%}">delete</a> <br>
            {% endif %}
            content :{{ post.body|slice:"50"|safe }}
        </li>
    {% empty %}
        <p>No blog is post on tag of {{cats}}</p>
    {% endfor %}
</ul>
{% endblock %}

ablog/theblog/templates/category_page.html
{% extends 'base.html' %}

{% block title %}
    category tags
{% endblock %}

{% block content %}
<h1>Categories</h1>
<ul>
    {% for cats in object_list %}
        <li> 
            <a href="{% url 'home:categoryViews' cats.name|slugify %}">{{cats.name}}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

ablog/theblog/templates/deletePost.html
{% extends 'base.html' %}

{% block title %}
    delete {{post.title_tag}}
{% endblock %}

{% block content %}
{% if user.is_authenticated and user.id == post.author.id %}
    <h1> Delete Post</h1>
        <br>
        <div class="form-group">
            <form method="POST">
                {% csrf_token %}
                <strong>Are you sure ?</strong><br>
                <button class="btn btn-secondary">Delete</button>
            </form>
        </div>
{% elif user.is_authenticated %}
    <p>You are not allowed to delete the post</p>
{% else %}
<p>Login is required</p>
<a href="{% url 'login' %}">Login Page!</a>
{% endif %}
{% endblock %}

ablog/theblog/templates/editPost.html
{% extends 'base.html' %}

{% block title %}
    edit blog{{post.title_tag}}
{% endblock %}

{% block content %}
{% if user.is_authenticated and user.id == post.author.id %}
    <h1>Add post...</h1>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{form.media}}
            {{form.as_p}}
            <button class="btn btn-secondary">Update</button>
        </form>
    </div>
{% elif user.is_authenticated %}
    <p>You are denial edit these post</p>
{% else %}
    <p>Login is required</p>
    <a href="{% url 'login' %}">Login Page!</a>
{% endif %}
{% endblock %}

ablog/theblog/templates/home.html
{% extends 'base.html' %}

{% block title %}
    home
{% endblock %}

{% block content %}
<h1>Post</h1>
<ul>
    {% for post in object_list %}
        <li> 
        <a href="{% url 'home:detail' post.pk %}"> title :{{ post.title }}</a><br>Category : <a href="{% url 'home:categoryViews' post.category|slugify %}">{{post.category}}</a><br>
        author :  {{ post.author}}  
        {% if user.is_authenticated %}
            {% if user.id == post.author.id %}
                 -<a href="{% url 'home:update' post.pk%}">edit</a>|| <a href="{% url 'home:delete' post.pk%}">delete</a>
            {% endif %}
         {% endif %}
            <br/>
            {{ post.snippet }}
<!--         content :{{ post.body|slice:"50"|safe }}
 -->        </li>
    {% endfor %}
</ul>
{% endblock %}

ablog/theblog/templates/post.html
{% extends 'base.html' %}

{% block title %}
    add post
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <h1>Add post...</h1>
    <div class="form-group">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{form.as_p}}
            <button class="btn btn-secondary">Post</button>
        </form>
        <br>
        <a class="btn btn-secondary" href="{% url 'home:home' %}">Home</a>
    </div>
    <script>
        let userid = "{{ user.id }}"
        document.getElementById('Theuser').value = userid;
    </script> 
{% else %}
    <p>Login is required</p>
    <a href="{% url 'login' %}">Login Page!</a>
{% endif %}
{% endblock %}